# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Rin Go' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rin Go

  pod 'Alamofire'

  target 'Rin GoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Rin GoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
